name: Build Docker Images, Push to Registry, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the private Ops repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: "recursive"

      - name: Generate data
        id: date
        run: echo "::set-output name=date::$(date +%Y-%m-%d-%Hh%Mm%Ss)"

      - name: Get short commit hash
        id: commit
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to private Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ops/backend.Dockerfile
          push: true
          tags: |
            lunary/backend:latest
            lunary/backend:rev-${{ steps.date.outputs.date }}-${{ steps.commit.outputs.hash }}
          platforms: linux/amd64

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ops/frontend.Dockerfile
          push: true
          tags: |
            lunary/frontend:latest
            lunary/frontend:rev-${{ steps.date.outputs.date }}-${{ steps.commit.outputs.hash }}
          platforms: linux/amd64

      - name: Build and push radar
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ops/radar.Dockerfile
          push: true
          tags: |
            lunary/radar:latest
            lunary/radar:rev-${{ steps.date.outputs.date }}-${{ steps.commit.outputs.hash }}
          platforms: linux/amd64

      - name: Build and push ml
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ops/ml.Dockerfile
          push: true
          tags: |
            lunary/ml:latest
            lunary/ml:rev-${{ steps.date.outputs.date }}-${{ steps.commit.outputs.hash }}
          platforms: linux/amd64

      - name: Build and push Monolith
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ops/Dockerfile
          push: true
          tags: |
            lunary/lunary-ee:latest
            lunary/lunary-ee:rev-${{ steps.date.outputs.date }}-${{ steps.commit.outputs.hash }}
          platforms: linux/amd64

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_IP_ADDRESS }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 3855
          script: |
            cd /opt/lunary
            docker compose pull
            docker compose down
            docker compose up -d
